project:
  type: book
  output-dir: docs

book:
  title: "R for Psychology"
  date: "3/14/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - organise.qmd
    - import.qmd
    - wrangle.qmd
    - describe.qmd
    - plot.qmd
    - inferences.qmd
    - maintain.qmd
    - contributing.qmd
    - datasets.qmd
    - appendix.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo

editor: source

